language: python
#python:
# - "2.6"
# - "2.7"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install libglpk-dev python-scipy libgmp-dev
  - cd /home/travis
  - wget http://clostridium.ucsd.edu/libsbml-5.6.0_built_with_py.tar.gz
  - tar xzf libsbml-5.6.0_built_with_py.tar.gz
  - cd libsbml-5.6.0/
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
install:
  - ln -s /usr/lib/python2.7/dist-packages/scipy ~/virtualenv/python2.7/lib/python2.7/site-packages/
  - pip install glpk 
# # command to run tests
script: python setup.py test
